version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3000" # Changed host port to 3001 to avoid conflict with frontend dev server
    volumes:
      - ./backend:/usr/src/app # Mount backend code
      - /usr/src/app/node_modules # Keep container's node_modules
    command: npx nodemon --watch src --ext ts --exec 'ts-node' src/server.ts
    environment:
      - NODE_ENV=development
      # Updated MongoDB connection string
      - MONGODB_URI=mongodb://mongo_user:mongo_password@mongo:27017/minesweeper_infinite?authSource=admin
      - DB_NAME=minesweeper_infinite
    depends_on:
      # Changed dependency from db to mongo
      - mongo
    networks:
      - minesweeper-net

  frontend:
    build: ./frontend
    # Override command to run Vite dev server and expose it
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/app # Mount local code for HMR
      - /app/node_modules # Keep container's node_modules separate
    # Expose Vite's port (defined in vite.config.js)
    ports:
      - "3000:3000"
    # Remove Nginx healthcheck - Vite dev server runs instead
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 15s
    networks:
      - minesweeper-net

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80" # Main entry point
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # Wait for frontend service container to start
      frontend:
        condition: service_started
      # Wait for backend container to start
      backend:
        condition: service_started
    networks:
      - minesweeper-net
    restart: unless-stopped

  mongo:
    image: mongo:latest # Use official MongoDB image
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user # Example user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password # Example password
      MONGO_INITDB_DATABASE: minesweeper_infinite # Database to initialize
    volumes:
      - mongo_data:/data/db # Persist MongoDB data
    ports:
      - "27017:27017" # Expose MongoDB port
    networks:
      - minesweeper-net

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    profiles: ["test"]
    volumes:
      - ./cypress/screenshots:/e2e/cypress/screenshots
      - ./cypress/videos:/e2e/cypress/videos
    depends_on:
      # Depends on the main proxy
      nginx:
        condition: service_started
    networks:
      - minesweeper-net
    environment:
      - CYPRESS_BASE_URL=http://nginx:80
    command: npx cypress run --browser chrome --headless

volumes:
  mongo_data:

networks:
  minesweeper-net:
    driver: bridge
