version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/bash -c "while sleep 1000; do :; done"
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      - NODE_ENV=development